import Head from "next/head"
import ShakespearesDen from "@/pages/ShakespearesDen"



export default function Home() {
  return (
    <>
      <Head>
        <title>Lo! A whisper in the wind.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ShakespearesDen />
      </main>
    </>
  )
}
