export { default as navbarProps } from "./navbarProps"
export { default as headerProps } from "./headerProps"
export { default as sidebarProps } from "./sidebarProps"
export { default as mainProps } from "./mainProps"
export { default as footerProps } from "./footerProps"
